import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const bannerJS =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'build');

const context = await esbuild.context({
  banner: {
    js: bannerJS
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@electron/remote',
    'node:process',
    'node:stream',
    'node:os',
    'node:path',
    'node:fs',
    'node:crypto',
    'node:util',
    'node:buffer',
    'node:events',
    'node:url',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  // React/JSX support
  loader: {
    '.tsx': 'tsx',
    '.ts': 'ts',
    '.js': 'js',
    '.css': 'css',
  },
  jsx: 'automatic',
  jsxImportSource: 'react',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}