import path from 'path'
import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import fs from 'fs'

const nodeBuiltins = [...builtins, ...builtins.map((mod) => `node:${mod}`)]

/**
 * PGlite plugin: patch postgres.js to load WASM/data from local plugin dir
 * instead of embedding in bundle or fetching from CDN.
 *
 * Strategy:
 * 1. Replace fetch() calls with a function that reads from __dirname
 * 2. Use Node.js fs.readFileSync to load files at runtime
 */
const pglitePlugin = {
  name: 'pglite-plugin',
  setup(build) {
    build.onLoad({ filter: /@electric-sql\/pglite/ }, async (args) => {
      let source = await fs.promises.readFile(args.path, 'utf8')

      // 1. Process shim
      source = `const process = {};\n${source}`

      if (args.path.endsWith('postgres.js')) {
        // Inject a fetch interceptor that reads from local filesystem
        const injectCode = [
          'var Module = moduleArg;',
          // Local file loader using Node.js fs
          `function _localFetch(name) {`,
          `  try {`,
          `    var fs = require('fs');`,
          `    var dir = __dirname || '.';`,
          `    var filePath = dir + '/' + name;`,
          `    if (fs.existsSync(filePath)) {`,
          `      var buf = fs.readFileSync(filePath);`,
          `      return Promise.resolve({`,
          `        ok: true, status: 200, url: name,`,
          `        arrayBuffer: function() { return Promise.resolve(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength)) },`,
          `        blob: function() { return Promise.resolve(new Blob([buf])) }`,
          `      });`,
          `    }`,
          `  } catch(e) {}`,
          `  return Promise.reject(new Error('Local file not found: ' + name));`,
          `}`,
        ].join('\n')

        source = source.replace('var Module = moduleArg;', injectCode)

        // Replace ALL fetch calls with _localFetch
        // fetch(packageName) in fetchRemotePackage
        source = source.replace(/fetch\(packageName\)/g, '_localFetch(packageName)')
        // fetch(binaryFile, {credentials:...}) in instantiateAsync
        source = source.replace(
          /fetch\(binaryFile, \{ credentials: 'same-origin' \}\)/g,
          "_localFetch(binaryFile.split('/').pop())"
        )
        // fetch(url, {credentials:...}) in readAsync
        source = source.replace(
          /fetch\(url, \{ credentials: 'same-origin' \}\)/g,
          "_localFetch(url.split('/').pop())"
        )

        // Also disable the instantiateStreaming fetch path
        source = source.replace(
          /if \(!binary && typeof WebAssembly\.instantiateStreaming/,
          'if(false&&typeof WebAssembly.instantiateStreaming'
        )
      }

      return { contents: source, loader: 'js' }
    })
  },
}


const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'build'

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    '@lexical/clipboard/clipboard',
    ...nodeBuiltins,
  ],
  format: 'cjs',
  inject: [path.resolve('import-meta-url-shim.js')],
  define: {
    'import.meta.url': 'import_meta_url',
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  metafile: true,
  plugins: [pglitePlugin],
  loader: {
    '.tsx': 'tsx',
    '.ts': 'ts',
    '.js': 'js',
    '.css': 'css',
  },
  jsx: 'automatic',
  jsxImportSource: 'react',
})

if (prod) {
  const result = await context.rebuild()
  fs.writeFileSync('meta.json', JSON.stringify(result.metafile))
  process.exit(0)
} else {
  await context.watch()
}
