/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SmartRAGPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var import_util = require("util");
var execAsync = (0, import_util.promisify)(import_child_process.exec);
var DEFAULT_SETTINGS = {
  chatLLM: {
    baseUrl: "https://coding.dashscope.aliyuncs.com/v1",
    apiKey: "sk-sp-5dd6c4a0e3a545e0920e147687ca685a",
    modelName: "glm-5",
    maxTokens: 2048,
    temperature: 0.7
  },
  lightRAGLLM: {
    baseUrl: "https://api.longcat.chat/openai/v1",
    apiKey: "ak_2pT3ly6Ix7iM56T7f37eq1It5fR2G",
    modelName: "LongCat-Flash-Lite"
  },
  semanticChunkLLM: {
    baseUrl: "https://coding.dashscope.aliyuncs.com/v1",
    apiKey: "sk-sp-5dd6c4a0e3a545e0920e147687ca685a",
    modelName: "glm-5"
  },
  lightRAGEmbedding: {
    baseUrl: "http://127.0.0.1:1234",
    modelName: "text-embedding-bge-m3",
    dimension: 1024
  },
  lightRAGWorkingDir: "~/.openclaw/lightrag-data"
};
var SmartRAGPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SmartRAGSettingTab(this.app, this));
    this.addRibbonIcon("brain", "Smart RAG", () => {
      this.openChatPanel();
    });
    this.addCommand({
      id: "open-chat-panel",
      name: "Open Chat Panel",
      callback: () => {
        this.openChatPanel();
      }
    });
    console.log("Smart RAG plugin loaded - v0.1.0-skeleton");
  }
  onunload() {
    console.log("Smart RAG plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openChatPanel() {
    console.log("Chat panel opened (placeholder - Phase 1 skeleton)");
  }
};
var SmartRAGSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.currentTab = "chat-llm";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Smart RAG Settings" });
    const tabContainer = containerEl.createDiv("smart-rag-tabs");
    const tabs = [
      { id: "chat-llm", label: "Chat LLM" },
      { id: "lightrag-llm", label: "LightRAG LLM" },
      { id: "chunk-llm", label: "Semantic Chunk" },
      { id: "embedding", label: "LightRAG Embedding" }
    ];
    const tabButtons = [];
    tabs.forEach((tab) => {
      const button = tabContainer.createEl("button", {
        text: tab.label,
        cls: "smart-rag-tab-button"
      });
      button.onclick = () => {
        this.currentTab = tab.id;
        this.display();
      };
      if (this.currentTab === tab.id) {
        button.addClass("smart-rag-tab-active");
      }
      tabButtons.push(button);
    });
    const contentContainer = containerEl.createDiv("smart-rag-tab-content");
    switch (this.currentTab) {
      case "chat-llm":
        this.renderChatLLMSettings(contentContainer);
        break;
      case "lightrag-llm":
        this.renderLightRAGLLMSettings(contentContainer);
        break;
      case "chunk-llm":
        this.renderSemanticChunkSettings(contentContainer);
        break;
      case "embedding":
        this.renderEmbeddingSettings(contentContainer);
        break;
    }
    new import_obsidian.Setting(containerEl).addButton((btn) => btn.setButtonText("Save Settings").setCta().onClick(async () => {
      await this.plugin.saveSettings();
      new import_obsidian.Notice("Settings saved!");
    }));
  }
  renderChatLLMSettings(container) {
    container.createEl("h3", { text: "Chat LLM Configuration" });
    new import_obsidian.Setting(container).setName("Base URL").setDesc("OpenAI-compatible API endpoint").addText((text) => text.setPlaceholder("https://api.example.com/v1").setValue(this.plugin.settings.chatLLM.baseUrl).onChange(async (value) => {
      this.plugin.settings.chatLLM.baseUrl = value;
    }));
    new import_obsidian.Setting(container).setName("API Key").setDesc("Authentication key for the API").addText((text) => text.setPlaceholder("sk-xxx").setValue(this.plugin.settings.chatLLM.apiKey).onChange(async (value) => {
      this.plugin.settings.chatLLM.apiKey = value;
    }));
    new import_obsidian.Setting(container).setName("Model Name").setDesc("Model identifier").addText((text) => text.setPlaceholder("model-name").setValue(this.plugin.settings.chatLLM.modelName).onChange(async (value) => {
      this.plugin.settings.chatLLM.modelName = value;
    }));
    new import_obsidian.Setting(container).setName("Max Tokens").setDesc("Maximum tokens for response").addText((text) => text.setPlaceholder("2048").setValue(String(this.plugin.settings.chatLLM.maxTokens || "")).onChange(async (value) => {
      this.plugin.settings.chatLLM.maxTokens = value ? parseInt(value) : void 0;
    }));
    new import_obsidian.Setting(container).setName("Temperature").setDesc("Response randomness (0.0-1.0)").addText((text) => text.setPlaceholder("0.7").setValue(String(this.plugin.settings.chatLLM.temperature || "")).onChange(async (value) => {
      this.plugin.settings.chatLLM.temperature = value ? parseFloat(value) : void 0;
    }));
  }
  renderLightRAGLLMSettings(container) {
    container.createEl("h3", { text: "LightRAG LLM Configuration" });
    new import_obsidian.Setting(container).setName("Base URL").setDesc("OpenAI-compatible API endpoint for LightRAG internal processing").addText((text) => text.setPlaceholder("https://api.example.com/v1").setValue(this.plugin.settings.lightRAGLLM.baseUrl).onChange(async (value) => {
      this.plugin.settings.lightRAGLLM.baseUrl = value;
    }));
    new import_obsidian.Setting(container).setName("API Key").setDesc("Authentication key for the API").addText((text) => text.setPlaceholder("sk-xxx").setValue(this.plugin.settings.lightRAGLLM.apiKey).onChange(async (value) => {
      this.plugin.settings.lightRAGLLM.apiKey = value;
    }));
    new import_obsidian.Setting(container).setName("Model Name").setDesc("Model identifier").addText((text) => text.setPlaceholder("model-name").setValue(this.plugin.settings.lightRAGLLM.modelName).onChange(async (value) => {
      this.plugin.settings.lightRAGLLM.modelName = value;
    }));
  }
  renderSemanticChunkSettings(container) {
    container.createEl("h3", { text: "Semantic Chunk LLM Configuration" });
    new import_obsidian.Setting(container).setName("Base URL").setDesc("OpenAI-compatible API endpoint for semantic text chunking").addText((text) => text.setPlaceholder("https://api.example.com/v1").setValue(this.plugin.settings.semanticChunkLLM.baseUrl).onChange(async (value) => {
      this.plugin.settings.semanticChunkLLM.baseUrl = value;
    }));
    new import_obsidian.Setting(container).setName("API Key").setDesc("Authentication key for the API").addText((text) => text.setPlaceholder("sk-xxx").setValue(this.plugin.settings.semanticChunkLLM.apiKey).onChange(async (value) => {
      this.plugin.settings.semanticChunkLLM.apiKey = value;
    }));
    new import_obsidian.Setting(container).setName("Model Name").setDesc("Model identifier").addText((text) => text.setPlaceholder("model-name").setValue(this.plugin.settings.semanticChunkLLM.modelName).onChange(async (value) => {
      this.plugin.settings.semanticChunkLLM.modelName = value;
    }));
  }
  renderEmbeddingSettings(container) {
    container.createEl("h3", { text: "LightRAG Embedding Configuration" });
    new import_obsidian.Setting(container).setName("Base URL").setDesc("Embedding API endpoint (e.g., LM Studio)").addText((text) => text.setPlaceholder("http://127.0.0.1:1234").setValue(this.plugin.settings.lightRAGEmbedding.baseUrl).onChange(async (value) => {
      this.plugin.settings.lightRAGEmbedding.baseUrl = value;
    }));
    new import_obsidian.Setting(container).setName("Model Name").setDesc("Embedding model identifier").addText((text) => text.setPlaceholder("text-embedding-bge-m3").setValue(this.plugin.settings.lightRAGEmbedding.modelName).onChange(async (value) => {
      this.plugin.settings.lightRAGEmbedding.modelName = value;
    }));
    new import_obsidian.Setting(container).setName("Dimension").setDesc("Vector dimension (e.g., 1024 for BGE-M3)").addText((text) => text.setPlaceholder("1024").setValue(String(this.plugin.settings.lightRAGEmbedding.dimension || "")).onChange(async (value) => {
      this.plugin.settings.lightRAGEmbedding.dimension = value ? parseInt(value) : void 0;
    }));
    container.createEl("hr");
    container.createEl("h4", { text: "\u2699\uFE0F LightRAG Server" });
    const statusSetting = new import_obsidian.Setting(container).setName("Server Status").setDesc("Check if LightRAG server is running on port 9621");
    const statusEl = statusSetting.settingEl.createDiv("smart-rag-server-status");
    statusEl.setText("Checking...");
    this.checkLightRAGServerStatus().then((status) => {
      if (status.running) {
        statusEl.setText("\u25CF Running");
        statusEl.style.color = "green";
      } else {
        statusEl.setText("\u25CB Stopped");
        statusEl.style.color = "red";
      }
    });
    const buttonContainer = container.createDiv("smart-rag-server-buttons");
    const startButton = buttonContainer.createEl("button", {
      text: "Start Server",
      cls: "mod-cta"
    });
    startButton.onclick = async () => {
      try {
        await this.startLightRAGServer();
        new import_obsidian.Notice("LightRAG server started!");
        this.display();
      } catch (error) {
        new import_obsidian.Notice(`Failed to start server: ${error.message}`);
      }
    };
    const stopButton = buttonContainer.createEl("button", {
      text: "Stop Server",
      cls: "mod-warning"
    });
    stopButton.onclick = async () => {
      try {
        await this.stopLightRAGServer();
        new import_obsidian.Notice("LightRAG server stopped!");
        this.display();
      } catch (error) {
        new import_obsidian.Notice(`Failed to stop server: ${error.message}`);
      }
    };
    new import_obsidian.Setting(container).setName("LightRAG Working Directory").setDesc("Shared LightRAG data directory (shared with Neural Composer)").addText((text) => text.setPlaceholder("~/.openclaw/lightrag-data").setValue(this.plugin.settings.lightRAGWorkingDir).onChange(async (value) => {
      this.plugin.settings.lightRAGWorkingDir = value;
    }));
  }
  async checkLightRAGServerStatus() {
    try {
      const response = await fetch("http://127.0.0.1:9621/health");
      return { running: response.ok };
    } catch (error) {
      return { running: false };
    }
  }
  async startLightRAGServer() {
    const startScript = "/Users/frankzhang/.openclaw/workspace/tools/lightrag-manager/start-lightrag.sh";
    try {
      const { stdout, stderr } = await execAsync(`bash "${startScript}"`);
      console.log("LightRAG Server started:", stdout);
      if (stderr) {
        console.warn("LightRAG Server stderr:", stderr);
      }
    } catch (error) {
      console.error("Failed to start LightRAG Server:", error);
      throw error;
    }
  }
  async stopLightRAGServer() {
    try {
      await execAsync("pkill -f lightrag-server");
      console.log("LightRAG Server stopped");
    } catch (error) {
      console.log("No LightRAG Server process found or already stopped");
    }
  }
};
