/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SmartRAGPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");
var import_child_process = require("child_process");
var import_util = require("util");

// src/services/connectionTester.ts
var import_obsidian = require("obsidian");
var ConnectionTester = class {
  /**
   * Test Chat/Semantic Chunk LLM connection
   * Sends a simple completion request to verify API works
   */
  async testLLMConnection(baseUrl, apiKey, modelName) {
    const startTime = Date.now();
    try {
      let normalizedUrl = baseUrl.replace(/\/+$/, "");
      if (!normalizedUrl.endsWith("/v1")) {
        normalizedUrl += "/v1";
      }
      const response = await (0, import_obsidian.requestUrl)({
        url: `${normalizedUrl}/chat/completions`,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: modelName,
          messages: [{ role: "user", content: 'Say "OK" if you can hear me.' }],
          max_tokens: 10
        })
      });
      const responseTime = Date.now() - startTime;
      if (response.status !== 200) {
        return {
          success: false,
          message: `API returned ${response.status}`,
          details: {
            error: response.text || "Unknown error",
            responseTime
          }
        };
      }
      const data = response.json;
      return {
        success: true,
        message: "Connection successful!",
        details: {
          model: data.model || modelName,
          responseTime
        }
      };
    } catch (error) {
      const responseTime = Date.now() - startTime;
      return {
        success: false,
        message: "Connection failed",
        details: {
          error: error instanceof Error ? error.message : String(error),
          responseTime
        }
      };
    }
  }
  /**
   * Test Embedding API connection
   * Sends a test text to get embeddings
   */
  async testEmbeddingConnection(baseUrl, modelName) {
    var _a, _b, _c;
    const startTime = Date.now();
    try {
      let normalizedUrl = baseUrl.replace(/\/+$/, "");
      if (!normalizedUrl.endsWith("/v1")) {
        normalizedUrl += "/v1";
      }
      const response = await (0, import_obsidian.requestUrl)({
        url: `${normalizedUrl}/embeddings`,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: modelName,
          input: "test"
        })
      });
      const responseTime = Date.now() - startTime;
      if (response.status !== 200) {
        return {
          success: false,
          message: `API returned ${response.status}`,
          details: {
            error: response.text || "Unknown error",
            responseTime
          }
        };
      }
      const data = response.json;
      const embeddingDim = ((_c = (_b = (_a = data.data) == null ? void 0 : _a[0]) == null ? void 0 : _b.embedding) == null ? void 0 : _c.length) || 0;
      return {
        success: true,
        message: "Connection successful!",
        details: {
          model: data.model || modelName,
          responseTime,
          error: `Embedding dimension: ${embeddingDim}`
        }
      };
    } catch (error) {
      const responseTime = Date.now() - startTime;
      return {
        success: false,
        message: "Connection failed",
        details: {
          error: error instanceof Error ? error.message : String(error),
          responseTime
        }
      };
    }
  }
  /**
   * Test LightRAG server health
   */
  async testLightRAGHealth() {
    const startTime = Date.now();
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: "http://127.0.0.1:9621/health",
        method: "GET"
      });
      const responseTime = Date.now() - startTime;
      if (response.status !== 200) {
        return {
          success: false,
          message: `LightRAG server returned ${response.status}`,
          details: {
            responseTime
          }
        };
      }
      const data = response.json;
      return {
        success: true,
        message: "LightRAG server is healthy",
        details: {
          model: data.llm_model,
          responseTime,
          error: `Status: ${data.status}`
        }
      };
    } catch (error) {
      const responseTime = Date.now() - startTime;
      return {
        success: false,
        message: "LightRAG server not reachable",
        details: {
          error: error instanceof Error ? error.message : "Server not running",
          responseTime
        }
      };
    }
  }
};

// src/ui/ChatPanel.ts
var import_obsidian3 = require("obsidian");

// src/services/llm.ts
var import_obsidian2 = require("obsidian");
var LLMService = class {
  /**
   * Send chat completion request
   */
  async chatCompletion(options) {
    var _a, _b, _c;
    const { baseUrl, apiKey, modelName, messages, maxTokens, temperature } = options;
    let normalizedUrl = baseUrl.replace(/\/+$/, "");
    if (!normalizedUrl.endsWith("/v1")) {
      normalizedUrl += "/v1";
    }
    const requestBody = {
      model: modelName,
      messages
    };
    if (maxTokens) requestBody.max_tokens = maxTokens;
    if (temperature !== void 0) requestBody.temperature = temperature;
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: `${normalizedUrl}/chat/completions`,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(requestBody)
      });
      if (response.status !== 200) {
        throw new Error(`API returned ${response.status}: ${response.text}`);
      }
      const data = response.json;
      const content = ((_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "";
      return {
        content,
        model: data.model || modelName,
        usage: data.usage ? {
          promptTokens: data.usage.prompt_tokens,
          completionTokens: data.usage.completion_tokens,
          totalTokens: data.usage.total_tokens
        } : void 0
      };
    } catch (error) {
      throw new Error(`Chat completion failed: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  /**
   * Simple chat with context
   */
  async chat(baseUrl, apiKey, modelName, userMessage, systemPrompt, maxTokens, temperature) {
    const messages = [];
    if (systemPrompt) {
      messages.push({ role: "system", content: systemPrompt });
    }
    messages.push({ role: "user", content: userMessage });
    const response = await this.chatCompletion({
      baseUrl,
      apiKey,
      modelName,
      messages,
      maxTokens,
      temperature
    });
    return response.content;
  }
};

// src/ui/ChatPanel.ts
var ChatPanel = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.messages = [];
    this.plugin = plugin;
    this.llmService = new LLMService();
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("smart-rag-chat-panel");
    const header = contentEl.createDiv("smart-rag-chat-header");
    header.createEl("h2", { text: "Smart RAG Chat" });
    this.messagesContainer = contentEl.createDiv("smart-rag-messages");
    const inputArea = contentEl.createDiv("smart-rag-input-area");
    this.inputEl = inputArea.createEl("textarea", {
      attr: {
        placeholder: "Type your message... (Shift+Enter for new line)",
        rows: "3"
      }
    });
    const buttonContainer = inputArea.createDiv("smart-rag-button-container");
    const sendButton = buttonContainer.createEl("button", {
      text: "Send",
      cls: "mod-cta"
    });
    sendButton.onclick = () => this.sendMessage();
    const clearButton = buttonContainer.createEl("button", {
      text: "Clear"
    });
    clearButton.onclick = () => this.clearMessages();
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    this.addMessage("assistant", "Hello! I'm Smart RAG. How can I help you today?");
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  async sendMessage() {
    const input = this.inputEl.value.trim();
    if (!input) return;
    this.inputEl.value = "";
    this.addMessage("user", input);
    this.messages.push({ role: "user", content: input });
    const loadingEl = this.addMessage("assistant", "Thinking...", true);
    try {
      const response = await this.llmService.chat(
        this.plugin.settings.chatLLM.baseUrl,
        this.plugin.settings.chatLLM.apiKey,
        this.plugin.settings.chatLLM.modelName,
        input,
        "You are a helpful AI assistant integrated into Obsidian. Be concise and helpful.",
        this.plugin.settings.chatLLM.maxTokens,
        this.plugin.settings.chatLLM.temperature
      );
      loadingEl.remove();
      this.addMessage("assistant", response);
      this.messages.push({ role: "assistant", content: response });
    } catch (error) {
      loadingEl.remove();
      this.addMessage("assistant", `\u274C Error: ${error instanceof Error ? error.message : String(error)}`);
      new import_obsidian3.Notice("Failed to get response from LLM");
    }
  }
  addMessage(role, content, isLoading = false) {
    const messageEl = this.messagesContainer.createDiv(`smart-rag-message smart-rag-message-${role}`);
    const roleEl = messageEl.createDiv("smart-rag-message-role");
    roleEl.setText(role === "user" ? "\u{1F464} You" : "\u{1F916} Assistant");
    const contentEl = messageEl.createDiv("smart-rag-message-content");
    if (isLoading) {
      contentEl.setText(content);
      messageEl.addClass("smart-rag-message-loading");
    } else {
      if (role === "assistant") {
        import_obsidian3.MarkdownRenderer.render(
          this.app,
          content,
          contentEl,
          "",
          this.plugin
        );
      } else {
        contentEl.setText(content);
      }
    }
    this.messagesContainer.scrollTop = this.messagesContainer.scrollHeight;
    return messageEl;
  }
  clearMessages() {
    this.messages = [];
    this.messagesContainer.empty();
    this.addMessage("assistant", "Chat cleared. How can I help you?");
  }
};

// src/main.ts
var execAsync = (0, import_util.promisify)(import_child_process.exec);
var connectionTester = new ConnectionTester();
var DEFAULT_SETTINGS = {
  chatLLM: {
    baseUrl: "https://coding.dashscope.aliyuncs.com/v1",
    apiKey: "sk-sp-5dd6c4a0e3a545e0920e147687ca685a",
    modelName: "glm-5",
    maxTokens: 2048,
    temperature: 0.7
  },
  lightRAGLLM: {
    baseUrl: "https://api.longcat.chat/openai/v1",
    apiKey: "ak_2pT3ly6Ix7iM56T7f37eq1It5fR2G",
    modelName: "LongCat-Flash-Lite"
  },
  semanticChunkLLM: {
    baseUrl: "https://coding.dashscope.aliyuncs.com/v1",
    apiKey: "sk-sp-5dd6c4a0e3a545e0920e147687ca685a",
    modelName: "glm-5",
    maxTokens: 1024,
    temperature: 0.1
  },
  lightRAGEmbedding: {
    baseUrl: "http://127.0.0.1:1234",
    modelName: "text-embedding-bge-m3",
    dimension: 1024
  },
  lightRAGWorkingDir: "~/.openclaw/lightrag-data"
};
var SmartRAGPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SmartRAGSettingTab(this.app, this));
    this.addRibbonIcon("brain", "Smart RAG", () => {
      this.openChatPanel();
    });
    this.addCommand({
      id: "open-chat-panel",
      name: "Open Chat Panel",
      callback: () => {
        this.openChatPanel();
      }
    });
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.setText("RAG: Checking...");
    this.updateStatusBar();
    this.statusCheckInterval = window.setInterval(() => {
      this.updateStatusBar();
    }, 5e3);
    console.log("Smart RAG plugin loaded - v0.3.0-chat");
  }
  onunload() {
    if (this.statusCheckInterval) {
      window.clearInterval(this.statusCheckInterval);
    }
    console.log("Smart RAG plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openChatPanel() {
    const chatPanel = new ChatPanel(this.app, this);
    chatPanel.open();
  }
  async updateStatusBar() {
    const status = await this.checkLightRAGServerStatus();
    switch (status.status) {
      case "running":
        this.statusBarItem.setText("RAG: \u25CF Running");
        this.statusBarItem.style.color = "#4CAF50";
        break;
      case "busy":
        this.statusBarItem.setText("RAG: \u25CF Busy");
        this.statusBarItem.style.color = "#FFC107";
        break;
      case "stopped":
        this.statusBarItem.setText("RAG: \u25CB Stopped");
        this.statusBarItem.style.color = "#F44336";
        break;
    }
  }
  async checkLightRAGServerStatus() {
    try {
      const { stdout } = await execAsync("ps aux | grep -v grep | grep lightrag-server");
      if (!stdout.trim()) {
        return { status: "stopped" };
      }
      try {
        const response = await fetch("http://127.0.0.1:9621/health");
        if (response.ok) {
          const data = await response.json();
          if (data.status === "busy" || data.processing) {
            return { status: "busy" };
          }
          return { status: "running" };
        }
        return { status: "stopped" };
      } catch (fetchError) {
        return { status: "busy" };
      }
    } catch (error) {
      return { status: "stopped" };
    }
  }
  async writeLightRAGConfig() {
    const configPath = "/Users/frankzhang/.openclaw/workspace/tools/lightrag-manager/lightrag-config.json";
    const config = {
      server: {
        host: "127.0.0.1",
        port: 9621,
        working_dir: this.settings.lightRAGWorkingDir.replace("~", process.env.HOME || "")
      },
      options: {
        log_level: "INFO",
        max_async: 4,
        timeout: 1200,
        chunking_strategy: "semantic"
      },
      llm: {
        base_url: this.settings.lightRAGLLM.baseUrl,
        api_key_env: this.settings.lightRAGLLM.apiKey,
        // 启动脚本读取 api_key_env
        model: this.settings.lightRAGLLM.modelName,
        provider: "custom",
        binding: "openai",
        temperature: 0.1,
        max_tokens: this.settings.lightRAGLLM.maxTokens || 2048
      },
      embedding: {
        base_url: this.settings.lightRAGEmbedding.baseUrl,
        api_key_env: "lm-studio",
        // Embedding 通常不需要 API key
        model: this.settings.lightRAGEmbedding.modelName,
        provider: "custom",
        binding: "openai",
        dimension: this.settings.lightRAGEmbedding.dimension || 1024
      }
    };
    const fs = window.require("fs");
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    console.log("LightRAG config written:", configPath);
    console.log("Config:", JSON.stringify(config, null, 2));
  }
  async startLightRAGServer() {
    await this.writeLightRAGConfig();
    const startScript = "/Users/frankzhang/.openclaw/workspace/tools/lightrag-manager/start-lightrag.sh";
    try {
      const { stdout, stderr } = await execAsync(`bash "${startScript}"`);
      console.log("LightRAG Server started:", stdout);
      if (stderr) {
        console.warn("LightRAG Server stderr:", stderr);
      }
    } catch (error) {
      console.error("Failed to start LightRAG Server:", error);
      throw error;
    }
  }
  async stopLightRAGServer() {
    try {
      await execAsync("pkill -f lightrag-server");
      console.log("LightRAG Server stopped");
    } catch (error) {
      console.log("No LightRAG Server process found or already stopped");
    }
  }
};
var SmartRAGSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.currentTab = "chat-llm";
    this.autoSaveTimeout = null;
    this.plugin = plugin;
  }
  /**
   * Show auto-save badge after input change
  	 * Auto-saves settings after 1 second of no changes
  	 */
  showAutoSaveBadge() {
    if (this.autoSaveTimeout) {
      window.clearTimeout(this.autoSaveTimeout);
    }
    this.autoSaveTimeout = window.setTimeout(async () => {
      await this.plugin.saveSettings();
      new import_obsidian4.Notice("\u2713 Auto-saved", 2e3);
      this.autoSaveTimeout = null;
    }, 1e3);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Smart RAG Settings" });
    const tabContainer = containerEl.createDiv("smart-rag-tabs");
    const tabs = [
      { id: "chat-llm", label: "Chat LLM" },
      { id: "lightrag-llm", label: "LightRAG LLM" },
      { id: "chunk-llm", label: "Semantic Chunk" },
      { id: "embedding", label: "LightRAG Embedding" }
    ];
    const tabButtons = [];
    tabs.forEach((tab) => {
      const button = tabContainer.createEl("button", {
        text: tab.label,
        cls: "smart-rag-tab-button"
      });
      button.onclick = () => {
        this.currentTab = tab.id;
        this.display();
      };
      if (this.currentTab === tab.id) {
        button.addClass("smart-rag-tab-active");
      }
      tabButtons.push(button);
    });
    const contentContainer = containerEl.createDiv("smart-rag-tab-content");
    switch (this.currentTab) {
      case "chat-llm":
        this.renderChatLLMSettings(contentContainer);
        break;
      case "lightrag-llm":
        this.renderLightRAGLLMSettings(contentContainer);
        break;
      case "chunk-llm":
        this.renderSemanticChunkSettings(contentContainer);
        break;
      case "embedding":
        this.renderEmbeddingSettings(containerEl);
        break;
    }
    new import_obsidian4.Setting(containerEl).addButton((btn) => btn.setButtonText("Save Settings").setCta().onClick(async () => {
      await this.plugin.saveSettings();
      new import_obsidian4.Notice("Settings saved!");
    }));
  }
  renderChatLLMSettings(container) {
    container.createEl("h3", { text: "Chat LLM Configuration" });
    new import_obsidian4.Setting(container).setName("Base URL").setDesc("OpenAI-compatible API endpoint").addText((text) => text.setPlaceholder("https://api.example.com/v1").setValue(this.plugin.settings.chatLLM.baseUrl).onChange(async (value) => {
      this.plugin.settings.chatLLM.baseUrl = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("API Key").setDesc("Authentication key for the API").addText((text) => text.setPlaceholder("sk-xxx").setValue(this.plugin.settings.chatLLM.apiKey).onChange(async (value) => {
      this.plugin.settings.chatLLM.apiKey = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Model Name").setDesc("Model identifier").addText((text) => text.setPlaceholder("model-name").setValue(this.plugin.settings.chatLLM.modelName).onChange(async (value) => {
      this.plugin.settings.chatLLM.modelName = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Max Tokens").setDesc("Maximum tokens for response").addText((text) => text.setPlaceholder("2048").setValue(String(this.plugin.settings.chatLLM.maxTokens || "")).onChange(async (value) => {
      this.plugin.settings.chatLLM.maxTokens = value ? parseInt(value) : void 0;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Temperature").setDesc("Response randomness (0.0-1.0)").addText((text) => text.setPlaceholder("0.7").setValue(String(this.plugin.settings.chatLLM.temperature || "")).onChange(async (value) => {
      this.plugin.settings.chatLLM.temperature = value ? parseFloat(value) : void 0;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Connection Test").setDesc("Test connection to Chat LLM API").addButton((btn) => btn.setButtonText("Test Connection").onClick(async () => {
      var _a, _b, _c;
      btn.setButtonText("Testing...");
      btn.setDisabled(true);
      const result = await connectionTester.testLLMConnection(
        this.plugin.settings.chatLLM.baseUrl,
        this.plugin.settings.chatLLM.apiKey,
        this.plugin.settings.chatLLM.modelName
      );
      btn.setButtonText("Test Connection");
      btn.setDisabled(false);
      if (result.success) {
        new import_obsidian4.Notice(`\u2705 ${result.message}
Model: ${(_a = result.details) == null ? void 0 : _a.model}
Response time: ${(_b = result.details) == null ? void 0 : _b.responseTime}ms`, 5e3);
      } else {
        new import_obsidian4.Notice(`\u274C ${result.message}
Error: ${(_c = result.details) == null ? void 0 : _c.error}`, 8e3);
      }
    }));
  }
  renderLightRAGLLMSettings(container) {
    container.createEl("h3", { text: "LightRAG LLM Configuration" });
    new import_obsidian4.Setting(container).setName("Base URL").setDesc("OpenAI-compatible API endpoint for LightRAG internal processing").addText((text) => text.setPlaceholder("https://api.example.com/v1").setValue(this.plugin.settings.lightRAGLLM.baseUrl).onChange(async (value) => {
      this.plugin.settings.lightRAGLLM.baseUrl = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("API Key").setDesc("Authentication key for the API").addText((text) => text.setPlaceholder("sk-xxx").setValue(this.plugin.settings.lightRAGLLM.apiKey).onChange(async (value) => {
      this.plugin.settings.lightRAGLLM.apiKey = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Model Name").setDesc("Model identifier").addText((text) => text.setPlaceholder("model-name").setValue(this.plugin.settings.lightRAGLLM.modelName).onChange(async (value) => {
      this.plugin.settings.lightRAGLLM.modelName = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Connection Test").setDesc("Test connection to LightRAG LLM API").addButton((btn) => btn.setButtonText("Test Connection").onClick(async () => {
      var _a, _b, _c;
      btn.setButtonText("Testing...");
      btn.setDisabled(true);
      const result = await connectionTester.testLLMConnection(
        this.plugin.settings.lightRAGLLM.baseUrl,
        this.plugin.settings.lightRAGLLM.apiKey,
        this.plugin.settings.lightRAGLLM.modelName
      );
      btn.setButtonText("Test Connection");
      btn.setDisabled(false);
      if (result.success) {
        new import_obsidian4.Notice(`\u2705 ${result.message}
Model: ${(_a = result.details) == null ? void 0 : _a.model}
Response time: ${(_b = result.details) == null ? void 0 : _b.responseTime}ms`, 5e3);
      } else {
        new import_obsidian4.Notice(`\u274C ${result.message}
Error: ${(_c = result.details) == null ? void 0 : _c.error}`, 8e3);
      }
    }));
  }
  renderSemanticChunkSettings(container) {
    container.createEl("h3", { text: "Semantic Chunk LLM Configuration" });
    new import_obsidian4.Setting(container).setName("Base URL").setDesc("OpenAI-compatible API endpoint for semantic text chunking").addText((text) => text.setPlaceholder("https://api.example.com/v1").setValue(this.plugin.settings.semanticChunkLLM.baseUrl).onChange(async (value) => {
      this.plugin.settings.semanticChunkLLM.baseUrl = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("API Key").setDesc("Authentication key for the API").addText((text) => text.setPlaceholder("sk-xxx").setValue(this.plugin.settings.semanticChunkLLM.apiKey).onChange(async (value) => {
      this.plugin.settings.semanticChunkLLM.apiKey = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Model Name").setDesc("Model identifier").addText((text) => text.setPlaceholder("model-name").setValue(this.plugin.settings.semanticChunkLLM.modelName).onChange(async (value) => {
      this.plugin.settings.semanticChunkLLM.modelName = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Max Tokens").setDesc("Maximum tokens for chunking analysis (1024 recommended)").addText((text) => text.setPlaceholder("1024").setValue(String(this.plugin.settings.semanticChunkLLM.maxTokens || "")).onChange(async (value) => {
      this.plugin.settings.semanticChunkLLM.maxTokens = value ? parseInt(value) : void 0;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Temperature").setDesc("Determinism for chunking (0.1-0.3 recommended for stable results)").addText((text) => text.setPlaceholder("0.1").setValue(String(this.plugin.settings.semanticChunkLLM.temperature || "")).onChange(async (value) => {
      this.plugin.settings.semanticChunkLLM.temperature = value ? parseFloat(value) : void 0;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Connection Test").setDesc("Test connection to Semantic Chunk LLM API").addButton((btn) => btn.setButtonText("Test Connection").onClick(async () => {
      var _a, _b, _c;
      btn.setButtonText("Testing...");
      btn.setDisabled(true);
      const result = await connectionTester.testLLMConnection(
        this.plugin.settings.semanticChunkLLM.baseUrl,
        this.plugin.settings.semanticChunkLLM.apiKey,
        this.plugin.settings.semanticChunkLLM.modelName
      );
      btn.setButtonText("Test Connection");
      btn.setDisabled(false);
      if (result.success) {
        new import_obsidian4.Notice(`\u2705 ${result.message}
Model: ${(_a = result.details) == null ? void 0 : _a.model}
Response time: ${(_b = result.details) == null ? void 0 : _b.responseTime}ms`, 5e3);
      } else {
        new import_obsidian4.Notice(`\u274C ${result.message}
Error: ${(_c = result.details) == null ? void 0 : _c.error}`, 8e3);
      }
    }));
  }
  renderEmbeddingSettings(container) {
    container.createEl("h3", { text: "LightRAG Embedding Configuration" });
    new import_obsidian4.Setting(container).setName("Base URL").setDesc("Embedding API endpoint (e.g., LM Studio)").addText((text) => text.setPlaceholder("http://127.0.0.1:1234").setValue(this.plugin.settings.lightRAGEmbedding.baseUrl).onChange(async (value) => {
      this.plugin.settings.lightRAGEmbedding.baseUrl = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Model Name").setDesc("Embedding model identifier").addText((text) => text.setPlaceholder("text-embedding-bge-m3").setValue(this.plugin.settings.lightRAGEmbedding.modelName).onChange(async (value) => {
      this.plugin.settings.lightRAGEmbedding.modelName = value;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Dimension").setDesc("Vector dimension (e.g., 1024 for BGE-M3)").addText((text) => text.setPlaceholder("1024").setValue(String(this.plugin.settings.lightRAGEmbedding.dimension || "")).onChange(async (value) => {
      this.plugin.settings.lightRAGEmbedding.dimension = value ? parseInt(value) : void 0;
      this.showAutoSaveBadge();
    }));
    new import_obsidian4.Setting(container).setName("Connection Test").setDesc("Test connection to Embedding API").addButton((btn) => btn.setButtonText("Test Connection").onClick(async () => {
      var _a, _b, _c;
      btn.setButtonText("Testing...");
      btn.setDisabled(true);
      const result = await connectionTester.testEmbeddingConnection(
        this.plugin.settings.lightRAGEmbedding.baseUrl,
        this.plugin.settings.lightRAGEmbedding.modelName
      );
      btn.setButtonText("Test Connection");
      btn.setDisabled(false);
      if (result.success) {
        new import_obsidian4.Notice(`\u2705 ${result.message}
${(_a = result.details) == null ? void 0 : _a.error}
Response time: ${(_b = result.details) == null ? void 0 : _b.responseTime}ms`, 5e3);
      } else {
        new import_obsidian4.Notice(`\u274C ${result.message}
Error: ${(_c = result.details) == null ? void 0 : _c.error}`, 8e3);
      }
    }));
    container.createEl("hr");
    container.createEl("h4", { text: "\u2699\uFE0F LightRAG Server" });
    const statusSetting = new import_obsidian4.Setting(container).setName("Server Status").setDesc("LightRAG server status (auto-refresh every 5 seconds)");
    const statusEl = statusSetting.settingEl.createDiv("smart-rag-server-status");
    statusEl.setText("Checking...");
    const updateStatus = async () => {
      const status = await this.plugin.checkLightRAGServerStatus();
      switch (status.status) {
        case "running":
          statusEl.setText("\u25CF Running");
          statusEl.style.color = "#4CAF50";
          break;
        case "busy":
          statusEl.setText("\u25CF Busy (Processing)");
          statusEl.style.color = "#FFC107";
          break;
        case "stopped":
          statusEl.setText("\u25CB Stopped");
          statusEl.style.color = "#F44336";
          break;
      }
    };
    updateStatus();
    const statusInterval = window.setInterval(updateStatus, 5e3);
    new import_obsidian4.Setting(container).setName("Server Controls").setDesc("Start or stop the LightRAG server").addButton((btn) => btn.setButtonText("Start Server").setCta().onClick(async () => {
      try {
        await this.plugin.startLightRAGServer();
        new import_obsidian4.Notice("LightRAG server started!");
        updateStatus();
      } catch (error) {
        new import_obsidian4.Notice(`Failed to start server: ${error.message}`);
      }
    })).addButton((btn) => btn.setButtonText("Stop Server").setWarning().onClick(async () => {
      try {
        await this.plugin.stopLightRAGServer();
        new import_obsidian4.Notice("LightRAG server stopped!");
        updateStatus();
      } catch (error) {
        new import_obsidian4.Notice(`Failed to stop server: ${error.message}`);
      }
    }));
    new import_obsidian4.Setting(container).setName("LightRAG Working Directory").setDesc("Shared LightRAG data directory (shared with Neural Composer)").addText((text) => text.setPlaceholder("~/.openclaw/lightrag-data").setValue(this.plugin.settings.lightRAGWorkingDir).onChange(async (value) => {
      this.plugin.settings.lightRAGWorkingDir = value;
    }));
  }
};
